package com.openheng.dao;

import java.util.Date;

public class Task {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task.id
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task.flow_id
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    private Long flow_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task.status
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task.source
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    private Byte source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task.gmt_create
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    private Date gmt_create;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task.gmt_modified
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    private Date gmt_modified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task.init_param
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    private String init_param;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task.id
     *
     * @return the value of swift_task.id
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task.id
     *
     * @param id the value for swift_task.id
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task.flow_id
     *
     * @return the value of swift_task.flow_id
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public Long getFlow_id() {
        return flow_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task.flow_id
     *
     * @param flow_id the value for swift_task.flow_id
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public void setFlow_id(Long flow_id) {
        this.flow_id = flow_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task.status
     *
     * @return the value of swift_task.status
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task.status
     *
     * @param status the value for swift_task.status
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task.source
     *
     * @return the value of swift_task.source
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public Byte getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task.source
     *
     * @param source the value for swift_task.source
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public void setSource(Byte source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task.gmt_create
     *
     * @return the value of swift_task.gmt_create
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public Date getGmt_create() {
        return gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task.gmt_create
     *
     * @param gmt_create the value for swift_task.gmt_create
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public void setGmt_create(Date gmt_create) {
        this.gmt_create = gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task.gmt_modified
     *
     * @return the value of swift_task.gmt_modified
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public Date getGmt_modified() {
        return gmt_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task.gmt_modified
     *
     * @param gmt_modified the value for swift_task.gmt_modified
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public void setGmt_modified(Date gmt_modified) {
        this.gmt_modified = gmt_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task.init_param
     *
     * @return the value of swift_task.init_param
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public String getInit_param() {
        return init_param;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task.init_param
     *
     * @param init_param the value for swift_task.init_param
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public void setInit_param(String init_param) {
        this.init_param = init_param == null ? null : init_param.trim();
    }
}