package com.openheng.dao;

public class TaskNodeExecutionInfoWithBLOBs extends TaskNodeExecutionInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task_node_execution_info.param
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    private String param;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task_node_execution_info.result
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    private String result;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task_node_execution_info.param
     *
     * @return the value of swift_task_node_execution_info.param
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public String getParam() {
        return param;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task_node_execution_info.param
     *
     * @param param the value for swift_task_node_execution_info.param
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public void setParam(String param) {
        this.param = param == null ? null : param.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task_node_execution_info.result
     *
     * @return the value of swift_task_node_execution_info.result
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task_node_execution_info.result
     *
     * @param result the value for swift_task_node_execution_info.result
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }
}