package com.openheng.dao;

import java.util.Date;

public class TaskNodeExecutionInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task_node_execution_info.id
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task_node_execution_info.task_id
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    private Long task_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task_node_execution_info.flow_id
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    private Long flow_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task_node_execution_info.node_id
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    private Long node_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task_node_execution_info.status
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task_node_execution_info.ip_info
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    private String ip_info;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task_node_execution_info.gmt_create
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    private Date gmt_create;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task_node_execution_info.gmt_modified
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    private Date gmt_modified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task_node_execution_info.id
     *
     * @return the value of swift_task_node_execution_info.id
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task_node_execution_info.id
     *
     * @param id the value for swift_task_node_execution_info.id
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task_node_execution_info.task_id
     *
     * @return the value of swift_task_node_execution_info.task_id
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public Long getTask_id() {
        return task_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task_node_execution_info.task_id
     *
     * @param task_id the value for swift_task_node_execution_info.task_id
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public void setTask_id(Long task_id) {
        this.task_id = task_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task_node_execution_info.flow_id
     *
     * @return the value of swift_task_node_execution_info.flow_id
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public Long getFlow_id() {
        return flow_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task_node_execution_info.flow_id
     *
     * @param flow_id the value for swift_task_node_execution_info.flow_id
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public void setFlow_id(Long flow_id) {
        this.flow_id = flow_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task_node_execution_info.node_id
     *
     * @return the value of swift_task_node_execution_info.node_id
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public Long getNode_id() {
        return node_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task_node_execution_info.node_id
     *
     * @param node_id the value for swift_task_node_execution_info.node_id
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public void setNode_id(Long node_id) {
        this.node_id = node_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task_node_execution_info.status
     *
     * @return the value of swift_task_node_execution_info.status
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task_node_execution_info.status
     *
     * @param status the value for swift_task_node_execution_info.status
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task_node_execution_info.ip_info
     *
     * @return the value of swift_task_node_execution_info.ip_info
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public String getIp_info() {
        return ip_info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task_node_execution_info.ip_info
     *
     * @param ip_info the value for swift_task_node_execution_info.ip_info
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public void setIp_info(String ip_info) {
        this.ip_info = ip_info == null ? null : ip_info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task_node_execution_info.gmt_create
     *
     * @return the value of swift_task_node_execution_info.gmt_create
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public Date getGmt_create() {
        return gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task_node_execution_info.gmt_create
     *
     * @param gmt_create the value for swift_task_node_execution_info.gmt_create
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public void setGmt_create(Date gmt_create) {
        this.gmt_create = gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task_node_execution_info.gmt_modified
     *
     * @return the value of swift_task_node_execution_info.gmt_modified
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public Date getGmt_modified() {
        return gmt_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task_node_execution_info.gmt_modified
     *
     * @param gmt_modified the value for swift_task_node_execution_info.gmt_modified
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public void setGmt_modified(Date gmt_modified) {
        this.gmt_modified = gmt_modified;
    }
}