package com.openheng.dao;

import java.util.Date;

public class TaskNodeExecutionInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task_node_execution_info.id
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task_node_execution_info.task_id
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    private Long taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task_node_execution_info.flow_id
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    private Long flowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task_node_execution_info.node_id
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    private Long nodeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task_node_execution_info.status
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task_node_execution_info.ip_info
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    private String ipInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task_node_execution_info.gmt_create
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task_node_execution_info.gmt_modified
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task_node_execution_info.id
     *
     * @return the value of swift_task_node_execution_info.id
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task_node_execution_info.id
     *
     * @param id the value for swift_task_node_execution_info.id
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task_node_execution_info.task_id
     *
     * @return the value of swift_task_node_execution_info.task_id
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task_node_execution_info.task_id
     *
     * @param taskId the value for swift_task_node_execution_info.task_id
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task_node_execution_info.flow_id
     *
     * @return the value of swift_task_node_execution_info.flow_id
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public Long getFlowId() {
        return flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task_node_execution_info.flow_id
     *
     * @param flowId the value for swift_task_node_execution_info.flow_id
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public void setFlowId(Long flowId) {
        this.flowId = flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task_node_execution_info.node_id
     *
     * @return the value of swift_task_node_execution_info.node_id
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public Long getNodeId() {
        return nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task_node_execution_info.node_id
     *
     * @param nodeId the value for swift_task_node_execution_info.node_id
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public void setNodeId(Long nodeId) {
        this.nodeId = nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task_node_execution_info.status
     *
     * @return the value of swift_task_node_execution_info.status
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task_node_execution_info.status
     *
     * @param status the value for swift_task_node_execution_info.status
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task_node_execution_info.ip_info
     *
     * @return the value of swift_task_node_execution_info.ip_info
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public String getIpInfo() {
        return ipInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task_node_execution_info.ip_info
     *
     * @param ipInfo the value for swift_task_node_execution_info.ip_info
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public void setIpInfo(String ipInfo) {
        this.ipInfo = ipInfo == null ? null : ipInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task_node_execution_info.gmt_create
     *
     * @return the value of swift_task_node_execution_info.gmt_create
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task_node_execution_info.gmt_create
     *
     * @param gmtCreate the value for swift_task_node_execution_info.gmt_create
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task_node_execution_info.gmt_modified
     *
     * @return the value of swift_task_node_execution_info.gmt_modified
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task_node_execution_info.gmt_modified
     *
     * @param gmtModified the value for swift_task_node_execution_info.gmt_modified
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}