package com.openheng.dao;

import java.util.Date;

public class TaskFlowNode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task_flow_node.id
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task_flow_node.biz_code
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    private Byte biz_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task_flow_node.flow_id
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    private Long flow_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task_flow_node.name
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task_flow_node.pre_node_id_list
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    private String pre_node_id_list;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task_flow_node.service_handler
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    private String service_handler;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task_flow_node.next_node_id_list
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    private String next_node_id_list;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task_flow_node.gmt_create
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    private Date gmt_create;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task_flow_node.gmt_modified
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    private Date gmt_modified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task_flow_node.id
     *
     * @return the value of swift_task_flow_node.id
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task_flow_node.id
     *
     * @param id the value for swift_task_flow_node.id
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task_flow_node.biz_code
     *
     * @return the value of swift_task_flow_node.biz_code
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public Byte getBiz_code() {
        return biz_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task_flow_node.biz_code
     *
     * @param biz_code the value for swift_task_flow_node.biz_code
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public void setBiz_code(Byte biz_code) {
        this.biz_code = biz_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task_flow_node.flow_id
     *
     * @return the value of swift_task_flow_node.flow_id
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public Long getFlow_id() {
        return flow_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task_flow_node.flow_id
     *
     * @param flow_id the value for swift_task_flow_node.flow_id
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public void setFlow_id(Long flow_id) {
        this.flow_id = flow_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task_flow_node.name
     *
     * @return the value of swift_task_flow_node.name
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task_flow_node.name
     *
     * @param name the value for swift_task_flow_node.name
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task_flow_node.pre_node_id_list
     *
     * @return the value of swift_task_flow_node.pre_node_id_list
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public String getPre_node_id_list() {
        return pre_node_id_list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task_flow_node.pre_node_id_list
     *
     * @param pre_node_id_list the value for swift_task_flow_node.pre_node_id_list
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public void setPre_node_id_list(String pre_node_id_list) {
        this.pre_node_id_list = pre_node_id_list == null ? null : pre_node_id_list.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task_flow_node.service_handler
     *
     * @return the value of swift_task_flow_node.service_handler
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public String getService_handler() {
        return service_handler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task_flow_node.service_handler
     *
     * @param service_handler the value for swift_task_flow_node.service_handler
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public void setService_handler(String service_handler) {
        this.service_handler = service_handler == null ? null : service_handler.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task_flow_node.next_node_id_list
     *
     * @return the value of swift_task_flow_node.next_node_id_list
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public String getNext_node_id_list() {
        return next_node_id_list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task_flow_node.next_node_id_list
     *
     * @param next_node_id_list the value for swift_task_flow_node.next_node_id_list
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public void setNext_node_id_list(String next_node_id_list) {
        this.next_node_id_list = next_node_id_list == null ? null : next_node_id_list.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task_flow_node.gmt_create
     *
     * @return the value of swift_task_flow_node.gmt_create
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public Date getGmt_create() {
        return gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task_flow_node.gmt_create
     *
     * @param gmt_create the value for swift_task_flow_node.gmt_create
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public void setGmt_create(Date gmt_create) {
        this.gmt_create = gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task_flow_node.gmt_modified
     *
     * @return the value of swift_task_flow_node.gmt_modified
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public Date getGmt_modified() {
        return gmt_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task_flow_node.gmt_modified
     *
     * @param gmt_modified the value for swift_task_flow_node.gmt_modified
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    public void setGmt_modified(Date gmt_modified) {
        this.gmt_modified = gmt_modified;
    }
}