package com.openheng.dao;

import java.util.Date;

public class TaskFlow {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task_flow.id
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task_flow.biz_code
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    private Byte bizCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task_flow.name
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task_flow.gmt_create
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task_flow.gmt_modified
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task_flow.id
     *
     * @return the value of swift_task_flow.id
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task_flow.id
     *
     * @param id the value for swift_task_flow.id
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task_flow.biz_code
     *
     * @return the value of swift_task_flow.biz_code
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public Byte getBizCode() {
        return bizCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task_flow.biz_code
     *
     * @param bizCode the value for swift_task_flow.biz_code
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public void setBizCode(Byte bizCode) {
        this.bizCode = bizCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task_flow.name
     *
     * @return the value of swift_task_flow.name
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task_flow.name
     *
     * @param name the value for swift_task_flow.name
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task_flow.gmt_create
     *
     * @return the value of swift_task_flow.gmt_create
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task_flow.gmt_create
     *
     * @param gmtCreate the value for swift_task_flow.gmt_create
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task_flow.gmt_modified
     *
     * @return the value of swift_task_flow.gmt_modified
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task_flow.gmt_modified
     *
     * @param gmtModified the value for swift_task_flow.gmt_modified
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}