package com.openheng.dao;

import com.openheng.dao.Task;
import com.openheng.dao.TaskExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swift_task
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    long countByExample(TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swift_task
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    int deleteByExample(TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swift_task
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swift_task
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    int insert(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swift_task
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    int insertSelective(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swift_task
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    List<Task> selectByExampleWithBLOBs(TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swift_task
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    List<Task> selectByExample(TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swift_task
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    Task selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swift_task
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    int updateByExampleSelective(@Param("record") Task record, @Param("example") TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swift_task
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("record") Task record, @Param("example") TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swift_task
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    int updateByExample(@Param("record") Task record, @Param("example") TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swift_task
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    int updateByPrimaryKeySelective(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swift_task
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swift_task
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    int updateByPrimaryKey(Task record);
}