package com.openheng.dao;

import java.util.Date;

public class TaskFlowNode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task_flow_node.id
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task_flow_node.biz_code
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    private Byte bizCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task_flow_node.flow_id
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    private Long flowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task_flow_node.name
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task_flow_node.pre_node_id_list
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    private String preNodeIdList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task_flow_node.service_handler
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    private String serviceHandler;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task_flow_node.next_node_id_list
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    private String nextNodeIdList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task_flow_node.gmt_create
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task_flow_node.gmt_modified
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task_flow_node.id
     *
     * @return the value of swift_task_flow_node.id
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task_flow_node.id
     *
     * @param id the value for swift_task_flow_node.id
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task_flow_node.biz_code
     *
     * @return the value of swift_task_flow_node.biz_code
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public Byte getBizCode() {
        return bizCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task_flow_node.biz_code
     *
     * @param bizCode the value for swift_task_flow_node.biz_code
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public void setBizCode(Byte bizCode) {
        this.bizCode = bizCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task_flow_node.flow_id
     *
     * @return the value of swift_task_flow_node.flow_id
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public Long getFlowId() {
        return flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task_flow_node.flow_id
     *
     * @param flowId the value for swift_task_flow_node.flow_id
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public void setFlowId(Long flowId) {
        this.flowId = flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task_flow_node.name
     *
     * @return the value of swift_task_flow_node.name
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task_flow_node.name
     *
     * @param name the value for swift_task_flow_node.name
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task_flow_node.pre_node_id_list
     *
     * @return the value of swift_task_flow_node.pre_node_id_list
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public String getPreNodeIdList() {
        return preNodeIdList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task_flow_node.pre_node_id_list
     *
     * @param preNodeIdList the value for swift_task_flow_node.pre_node_id_list
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public void setPreNodeIdList(String preNodeIdList) {
        this.preNodeIdList = preNodeIdList == null ? null : preNodeIdList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task_flow_node.service_handler
     *
     * @return the value of swift_task_flow_node.service_handler
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public String getServiceHandler() {
        return serviceHandler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task_flow_node.service_handler
     *
     * @param serviceHandler the value for swift_task_flow_node.service_handler
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public void setServiceHandler(String serviceHandler) {
        this.serviceHandler = serviceHandler == null ? null : serviceHandler.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task_flow_node.next_node_id_list
     *
     * @return the value of swift_task_flow_node.next_node_id_list
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public String getNextNodeIdList() {
        return nextNodeIdList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task_flow_node.next_node_id_list
     *
     * @param nextNodeIdList the value for swift_task_flow_node.next_node_id_list
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public void setNextNodeIdList(String nextNodeIdList) {
        this.nextNodeIdList = nextNodeIdList == null ? null : nextNodeIdList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task_flow_node.gmt_create
     *
     * @return the value of swift_task_flow_node.gmt_create
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task_flow_node.gmt_create
     *
     * @param gmtCreate the value for swift_task_flow_node.gmt_create
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task_flow_node.gmt_modified
     *
     * @return the value of swift_task_flow_node.gmt_modified
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task_flow_node.gmt_modified
     *
     * @param gmtModified the value for swift_task_flow_node.gmt_modified
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}