package com.openheng.dao;

import java.util.Date;

public class Task {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task.id
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task.flow_id
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    private Long flowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task.status
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task.source
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    private Byte source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task.gmt_create
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task.gmt_modified
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swift_task.init_param
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    private String initParam;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task.id
     *
     * @return the value of swift_task.id
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task.id
     *
     * @param id the value for swift_task.id
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task.flow_id
     *
     * @return the value of swift_task.flow_id
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public Long getFlowId() {
        return flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task.flow_id
     *
     * @param flowId the value for swift_task.flow_id
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public void setFlowId(Long flowId) {
        this.flowId = flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task.status
     *
     * @return the value of swift_task.status
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task.status
     *
     * @param status the value for swift_task.status
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task.source
     *
     * @return the value of swift_task.source
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public Byte getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task.source
     *
     * @param source the value for swift_task.source
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public void setSource(Byte source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task.gmt_create
     *
     * @return the value of swift_task.gmt_create
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task.gmt_create
     *
     * @param gmtCreate the value for swift_task.gmt_create
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task.gmt_modified
     *
     * @return the value of swift_task.gmt_modified
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task.gmt_modified
     *
     * @param gmtModified the value for swift_task.gmt_modified
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swift_task.init_param
     *
     * @return the value of swift_task.init_param
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public String getInitParam() {
        return initParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swift_task.init_param
     *
     * @param initParam the value for swift_task.init_param
     *
     * @mbg.generated Thu Aug 24 22:00:22 CST 2023
     */
    public void setInitParam(String initParam) {
        this.initParam = initParam == null ? null : initParam.trim();
    }
}