package com.openheng.dao;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface TaskNodeExecutionInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swift_task_node_execution_info
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    long countByExample(TaskNodeExecutionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swift_task_node_execution_info
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    int deleteByExample(TaskNodeExecutionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swift_task_node_execution_info
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swift_task_node_execution_info
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    int insert(TaskNodeExecutionInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swift_task_node_execution_info
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    int insertSelective(TaskNodeExecutionInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swift_task_node_execution_info
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    List<TaskNodeExecutionInfoWithBLOBs> selectByExampleWithBLOBs(TaskNodeExecutionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swift_task_node_execution_info
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    List<TaskNodeExecutionInfo> selectByExample(TaskNodeExecutionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swift_task_node_execution_info
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    TaskNodeExecutionInfoWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swift_task_node_execution_info
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    int updateByExampleSelective(@Param("record") TaskNodeExecutionInfoWithBLOBs record, @Param("example") TaskNodeExecutionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swift_task_node_execution_info
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("record") TaskNodeExecutionInfoWithBLOBs record, @Param("example") TaskNodeExecutionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swift_task_node_execution_info
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    int updateByExample(@Param("record") TaskNodeExecutionInfo record, @Param("example") TaskNodeExecutionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swift_task_node_execution_info
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    int updateByPrimaryKeySelective(TaskNodeExecutionInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swift_task_node_execution_info
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(TaskNodeExecutionInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swift_task_node_execution_info
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    int updateByPrimaryKey(TaskNodeExecutionInfo record);
}