package com.openheng.dao;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface TaskFlowNodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swift_task_flow_node
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    long countByExample(TaskFlowNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swift_task_flow_node
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    int deleteByExample(TaskFlowNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swift_task_flow_node
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swift_task_flow_node
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    int insert(TaskFlowNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swift_task_flow_node
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    int insertSelective(TaskFlowNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swift_task_flow_node
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    List<TaskFlowNode> selectByExample(TaskFlowNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swift_task_flow_node
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    TaskFlowNode selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swift_task_flow_node
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    int updateByExampleSelective(@Param("record") TaskFlowNode record, @Param("example") TaskFlowNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swift_task_flow_node
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    int updateByExample(@Param("record") TaskFlowNode record, @Param("example") TaskFlowNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swift_task_flow_node
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    int updateByPrimaryKeySelective(TaskFlowNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swift_task_flow_node
     *
     * @mbg.generated Thu Aug 03 19:59:07 CST 2023
     */
    int updateByPrimaryKey(TaskFlowNode record);
}